### ISSUE TITLE
Remove rotate_EXP and translate_EXP

### ISSUE THREAD

**Issue by phlsa** [hfg-gmuend/gmynd#1]
With the addition of transform objects and the related methods, is there still a reason to keep direct transformation functions around?

**Comment by phlsa** [comment]
What do you think @sinuit ?

**Comment by bohnacker** [comment]
Since it might be confusing if rotate_EXP or translate_EXP will replace an existing tranformation or will be added to the end of the existing transformations, it's better to remove these function. We still could think of having a funciton like "replaceTransform".
