### ISSUE TITLE
avoid redundant property in mergeData()

### ISSUE THREAD

**Issue by caitoor** [hfg-gmuend/gmynd#8]
when merging two arrays with mergeData() using different property names (e.g. "countryCode" in the first array and "alpha3Code" in the second), the resulting array objects will have both properties with the same value. Do we intend to use deleteProps() afterwards or should we change that?

**Comment by bohnacker** [comment]
I already came across this when testing stuff. Maybe we could just keep the prop name of the first array.

**Comment by caitoor** [comment]
fixed

**Comment by bohnacker** [comment]
Thanks a lot!
